# Generated by Django 4.0.5 on 2022-07-01 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='students/bulkupload/')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kankor_id', models.CharField(max_length=200, unique=True)),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('grand_father_name', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('province', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('خانم', 'خانم'), ('آقا', 'آقا')], default='آقا', max_length=30)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=30)),
                ('status', models.CharField(choices=[('فعال', 'فعال'), ('تعجیل', 'تعجیل'), ('چانس', 'چانس'), ('ناکام', 'ناکام'), ('غیر فعال', 'غیر فعال')], default='فعال', max_length=30)),
                ('adminssion_date', models.DateField(auto_now_add=True)),
                ('cart', models.CharField(choices=[('تذکره برقی', 'تذکره برقی'), ('تذکره کاغذی', 'تذکره کاغذی')], default='تذکره برقی', max_length=30)),
                ('cart_number', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('page_number', models.CharField(blank=True, max_length=200, null=True)),
                ('register_number', models.CharField(blank=True, max_length=200, null=True)),
                ('volume_number', models.CharField(blank=True, max_length=200, null=True)),
                ('cart_image', models.ImageField(default='cart.jpg', upload_to='images/cart')),
                ('hostel', models.CharField(choices=[('بلی', 'بلی'), ('نخیر', 'نخیر')], default='نخیر', max_length=20)),
                ('wing_number', models.IntegerField(blank=True, null=True)),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('graduated_from_school', models.DateField(blank=True, null=True)),
                ('rel_with_std', models.CharField(blank=True, max_length=200, null=True)),
                ('rel_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rel_job', models.CharField(blank=True, max_length=200, null=True)),
                ('rel_phone1', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('rel_phone2', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('rel_current_address', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(default='student.jpg', upload_to='images/students')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.semester')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
