# Generated by Django 4.0.5 on 2022-07-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
