# Generated by Django 4.0.5 on 2022-07-01 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luncher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='نام استاد که ارزیابی میشود')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('کاملا مخالف', 'کاملا مخالف'), ('مخالف', 'مخالف'), ('بعضی اوقات', 'بعضی اوقات'), ('موافق', 'موافق'), ('کاملا موافق', 'کاملا موافق')], max_length=200, verbose_name='استاد تسلط کامل بر موضوعی که تدریس میکند دارد.')),
                ('descipline', models.CharField(choices=[('کاملا مخالف', 'کاملا مخالف'), ('مخالف', 'مخالف'), ('بعضی اوقات', 'بعضی اوقات'), ('موافق', 'موافق'), ('کاملا موافق', 'کاملا موافق')], max_length=200, verbose_name='استاد در وقت معین به صنف آمده و خارج میشود و نهایت استفاده را از ساعت درسی میکند.')),
                ('ability_to_explain', models.CharField(choices=[('کاملا مخالف', 'کاملا مخالف'), ('مخالف', 'مخالف'), ('بعضی اوقات', 'بعضی اوقات'), ('موافق', 'موافق'), ('کاملا موافق', 'کاملا موافق')], max_length=200, verbose_name='با آنکه میدانم استاد تسلط کامل بالای موضوع دارد ولی نحوه تدریس شان قابل فهم نیست.')),
                ('coaporation_with_students', models.CharField(choices=[('کاملا مخالف', 'کاملا مخالف'), ('مخالف', 'مخالف'), ('بعضی اوقات', 'بعضی اوقات'), ('موافق', 'موافق'), ('کاملا موافق', 'کاملا موافق')], max_length=200, verbose_name='نحوه تدریس استاد مشارکتی نیست و شاگردان مشارکتی در درس ها ندارد.')),
                ('expectations', models.CharField(choices=[('کاملا مخالف', 'کاملا مخالف'), ('مخالف', 'مخالف'), ('بعضی اوقات', 'بعضی اوقات'), ('موافق', 'موافق'), ('کاملا موافق', 'کاملا موافق')], max_length=200, verbose_name='توقع استاد بیشتر از چیزی هست که با شاگردان تدریس میکند.')),
                ('discriminations', models.CharField(choices=[('کاملا مخالف', 'کاملا مخالف'), ('مخالف', 'مخالف'), ('بعضی اوقات', 'بعضی اوقات'), ('موافق', 'موافق'), ('کاملا موافق', 'کاملا موافق')], max_length=255, verbose_name='استاد هیچ گونه تمایلی به تبعیض قایل شدن بین شاگردان اش نیست و شاگردان را به هم پذیری دعوت میکند.')),
                ('ethics', models.CharField(choices=[('کاملا مخالف', 'کاملا مخالف'), ('مخالف', 'مخالف'), ('بعضی اوقات', 'بعضی اوقات'), ('موافق', 'موافق'), ('کاملا موافق', 'کاملا موافق')], max_length=255, verbose_name='استاد از اخلاق نیکو و پسندیده ای برخوردار نیست.')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات اضافی')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.evaluation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
