# Generated by Django 4.1.2 on 2022-11-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_education_user_remove_experience_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='file',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='file',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='years',
        ),
    ]
