# Generated by Django 4.1.2 on 2022-11-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_education_file_remove_experience_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cart_image',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='cart_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='national_cart',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='register_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='volume',
        ),
    ]
