# Generated by Django 4.1.2 on 2022-11-28 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_remove_employee_cart_image_and_more'),
        ('departments', '0005_delete_schedule'),
        ('subjects', '0001_initial'),
        ('courses', '0003_session_current_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهار شنبه', 'چهار شنبه'), ('پنج شنبه', 'پنج شنبه')], max_length=50)),
                ('hours', models.CharField(choices=[('اول', 'اول'), ('دوم', 'دوم'), ('سوم', 'سوم'), ('چهارم', 'چهارم')], max_length=50)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
    ]
