# Generated by Django 4.1.2 on 2022-11-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='days',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hours',
            field=models.CharField(max_length=250),
        ),
    ]
