# Generated by Django 4.1.2 on 2022-11-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_session',
            field=models.BooleanField(default=False),
        ),
    ]
