# Generated by Django 4.0.1 on 2022-09-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_phone'),
        ('tasks', '0003_remove_assignment_expir_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='is_submitted',
            field=models.ManyToManyField(blank=True, to='students.Student'),
        ),
    ]
