# Generated by Django 4.0.5 on 2022-07-01 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='subjects/bulk/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('credit', models.IntegerField()),
                ('slug', models.SlugField(max_length=200)),
                ('subject_type', models.CharField(choices=[('اصلی', 'اصلی'), ('فرعی', 'فرعی')], default='اصلی', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.semester')),
            ],
        ),
    ]
