# Generated by Django 4.1.2 on 2022-11-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
