# Generated by Django 4.1.2 on 2022-12-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_delete_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
